// --- PROJECTS ---------------------------------------------------------------
export const projects = [
  {
    id: '-erp',
    slug: 'nexus-erp',
    title: 'Nexus ERP Platform',
    systemType: 'Enterprise Resource Planning System',
    category: 'Enterprise',
    industry: 'Manufacturing',
    shortDesc: 'End-to-end enterprise resource planning system built for a 500-employee manufacturing company. Covers inventory, HR, payroll, procurement, and real-time financial reporting.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80',
      'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=1200&q=80',
    ],
    tags: ['React', 'Node.js', 'PostgreSQL', 'Docker'],
    overview: 'A comprehensive ERP system covering inventory, HR, payroll, procurement, and financial reporting.',
    problem: 'The client operated on disconnected spreadsheets and legacy software, causing data inconsistencies and operational delays.',
    solution: 'We built a unified ERP platform with real-time dashboards, automated workflows, and role-based access control.',
    features: ['Inventory Management', 'HR & Payroll', 'Procurement Module', 'Financial Reporting', 'Supplier Portal', 'Analytics Dashboard'],
    technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    results: [
      { metric: 'Operational Efficiency', value: '+65%' },
      { metric: 'Data Entry Time Reduced', value: '-80%' },
      { metric: 'Report Generation', value: 'Realtime' },
      { metric: 'ROI in Year 1', value: '340%' },
    ],
    testimonial: {
      quote: 'PROGREX delivered a system that transformed how we operate. Best investment we ever made.',
      author: 'Marcus Thompson',
      role: 'COO, Nexus Manufacturing',
    },
  },
  {
    id: 'edutrack-lms',
    slug: 'edutrack-lms',
    title: 'EduTrack LMS',
    systemType: 'Learning Management System',
    category: 'Web',
    industry: 'Education',
    shortDesc: 'Full-featured learning management system deployed across a network of 12 schools in the Philippines. Supports online courses, live sessions, parent monitoring, and Stripe-integrated fee collection.',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&q=80',
      'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=1200&q=80',
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&q=80',
      'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=1200&q=80',
    ],
    tags: ['Next.js', 'Prisma', 'PostgreSQL', 'Stripe'],
    overview: 'A scalable LMS with online courses, assessments, live sessions, parent monitoring, and payment integration.',
    problem: 'Schools needed a unified digital platform for remote learning, grading, and parent-teacher communication.',
    solution: 'We built EduTrack — a multi-tenant LMS with school-specific branding, student dashboards, and integrated Stripe payment.',
    features: ['Course Management', 'Live Sessions', 'Assessment Engine', 'Parent Portal', 'Grade Tracking', 'Certificate Generation'],
    technologies: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Stripe', 'Zoom API', 'Vercel'],
    results: [
      { metric: 'Students Enrolled', value: '18,000+' },
      { metric: 'Course Completion Rate', value: '87%' },
      { metric: 'Schools on Platform', value: '12' },
      { metric: 'Parent Satisfaction', value: '4.9/5' },
    ],
    testimonial: {
      quote: 'EduTrack has become the backbone of our digital education strategy. Outstanding platform.',
      author: 'Dr. Elena Santos',
      role: 'Director, EduNet Schools',
    },
  },
  {
    id: 'swiftcart-ecommerce',
    slug: 'swiftcart-ecommerce',
    title: 'SwiftCart E-Commerce',
    systemType: 'E-Commerce Platform',
    category: 'E-commerce',
    industry: 'Retail',
    shortDesc: 'High-conversion multi-vendor e-commerce platform with real-time inventory and advanced analytics. Powers B2C and B2B sales with optimized checkout flows and full logistics integration.',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80',
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80',
      'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&q=80',
      'https://images.unsplash.com/photo-1571721795195-a2ca2d3370a9?w=1200&q=80',
    ],
    tags: ['Next.js', 'MongoDB', 'Stripe', 'AWS'],
    overview: 'A B2C/B2B e-commerce platform supporting multiple vendors, dynamic pricing, and logistics integration.',
    problem: 'The client had a basic website with poor UX and no inventory management, losing 40% of potential customers at checkout.',
    solution: 'We rebuilt the entire platform with Next.js, optimized checkout flow, multi-vendor support, and real-time inventory tracking.',
    features: ['Multi-Vendor Support', 'Dynamic Pricing', 'Real-Time Inventory', 'Advanced Analytics', 'Logistics Integration', 'Mobile App'],
    technologies: ['Next.js', 'MongoDB', 'Stripe', 'AWS S3', 'Redis', 'React Native', 'Elasticsearch'],
    results: [
      { metric: 'Conversion Rate', value: '+127%' },
      { metric: 'Page Load Speed', value: '1.2s avg' },
      { metric: 'Monthly Revenue Growth', value: '+89%' },
      { metric: 'Cart Abandonment', value: '-45%' },
    ],
    testimonial: {
      quote: 'Our sales literally doubled in 3 months after launching the new platform. PROGREX delivered.',
      author: 'Jei Santos',
      role: 'CEO, SwiftCart Retail',
    },
  },
  {
    id: 'meditrack-hms',
    slug: 'meditrack-hms',
    title: 'MediTrack Hospital Management',
    systemType: 'Hospital Management System',
    category: 'Enterprise',
    industry: 'Healthcare',
    shortDesc: 'Comprehensive hospital management system covering patient records, billing, pharmacy, and telemedicine. Fully HIPAA-compliant with EMR/EHR, appointment scheduling, and automated insurance billing.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80',
      'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=1200&q=80',
      'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=1200&q=80',
      'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=1200&q=80',
    ],
    tags: ['React', 'Python', 'PostgreSQL', 'WebRTC'],
    overview: 'A full-stack HMS with EMR/EHR, appointment scheduling, pharmacy management, and telemedicine.',
    problem: 'Hospital operations relied on paper-based records causing delays, errors, and compliance risks.',
    solution: 'MediTrack digitizes all hospital operations with HIPAA-compliant patient records, automated billing, and telemedicine.',
    features: ['EMR/EHR', 'Appointment Scheduling', 'Pharmacy Management', 'Telemedicine', 'Billing & Insurance', 'Lab Results'],
    technologies: ['React', 'Python/FastAPI', 'PostgreSQL', 'WebRTC', 'Redis', 'AWS', 'Docker'],
    results: [
      { metric: 'Patient Processing Time', value: '-60%' },
      { metric: 'Billing Accuracy', value: '99.8%' },
      { metric: 'Telemedicine Consultations', value: '2,400/mo' },
      { metric: 'Staff Satisfaction', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'MediTrack revolutionized our operations. Patient care quality has improved dramatically.',
      author: 'Dr. Mark Reyes',
      role: 'Chief Medical Officer',
    },
  },
  {
    id: 'propmanage-saas',
    slug: 'propmanage-saas',
    title: 'PropManage SaaS',
    systemType: 'Property Management System',
    category: 'SaaS',
    industry: 'Real Estate',
    shortDesc: 'Property management SaaS platform enabling landlords to manage tenants, rent collection, maintenance, and financial reports. Automates payment reminders via SMS and email with real-time multi-property dashboards.',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
    ],
    tags: ['Next.js', 'Stripe', 'PostgreSQL', 'Twilio'],
    overview: 'Multi-tenant SaaS for property managers with automated rent collection, maintenance tickets, and financial reports.',
    problem: 'Property managers used spreadsheets and manual bank transfers causing payment delays and poor tenant communication.',
    solution: 'PropManage automates rent collection, sends reminders via SMS/email, and provides financial dashboards.',
    features: ['Tenant Portal', 'Automated Rent Collection', 'Maintenance Tickets', 'SMS/Email Notifications', 'Financial Reports', 'Multi-Property'],
    technologies: ['Next.js', 'TypeScript', 'Stripe', 'Twilio', 'PostgreSQL', 'Prisma', 'Vercel'],
    results: [
      { metric: 'On-Time Rent Collection', value: '97%' },
      { metric: 'Admin Time Saved', value: '15h/week' },
      { metric: 'Tenants Managed', value: '3,200+' },
      { metric: 'Late Payments', value: '-72%' },
    ],
    testimonial: {
      quote: 'PropManage pays for itself every month. Absolutely transformed our property business.',
      author: 'Lisa Chen',
      role: 'Managing Director, Chen Properties',
    },
  },
  {
    id: 'campusvote-academic',
    slug: 'campusvote-academic',
    title: 'CampusVote System',
    systemType: 'Online Student Voting System',
    category: 'Academic',
    industry: 'Education',
    shortDesc: 'Secure online student election system with biometric verification and real-time vote counting. Features encrypted ballot storage, audit trails, and a live results broadcast dashboard for campus-wide elections.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&q=80',
      'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?w=1200&q=80',
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80',
      'https://images.unsplash.com/photo-1496200186974-4293800e2c20?w=1200&q=80',
    ],
    tags: ['React', 'Laravel', 'MySQL', 'WebSocket'],
    overview: 'A capstone project for university student government elections with biometric login and live results.',
    problem: 'Traditional paper elections were slow, costly, and vulnerable to fraud. The student government needed a digital solution.',
    solution: 'We built CampusVote with fingerprint authentication, encrypted vote storage, and real-time result broadcasting.',
    features: ['Biometric Login', 'Encrypted Voting', 'Live Results Dashboard', 'Audit Trail', 'Admin Panel', 'Mobile Responsive'],
    technologies: ['React', 'Laravel', 'MySQL', 'WebSocket', 'Fingerprint.js', 'Bootstrap'],
    results: [
      { metric: 'Voter Turnout', value: '+43%' },
      { metric: 'Election Duration', value: '6h (previously 3 days)' },
      { metric: 'Zero Fraud Incidents', value: '100%' },
      { metric: 'Student Satisfaction', value: '4.7/5' },
    ],
    testimonial: {
      quote: 'The most impressive capstone system our panel has ever reviewed. Truly production-ready.',
      author: 'Prof. Ana Reyes',
      role: 'Computer Science Department',
    },
  },
  {
    id: 'smartfactory-iot',
    slug: 'smartfactory-iot',
    title: 'SmartFactory IoT Monitor',
    systemType: 'IoT Monitoring Platform',
    category: 'Hardware',
    industry: 'Industrial / Manufacturing',
    shortDesc: 'Industrial IoT monitoring platform connecting 200+ factory floor sensors to a centralized cloud dashboard with predictive maintenance analytics. Features real-time alerting, OTA firmware updates, and automated downtime reporting.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80',
      'https://images.unsplash.com/photo-1565514158740-064f34bd6cfd?w=1200&q=80',
      'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    ],
    tags: ['Arduino', 'MQTT', 'AWS IoT', 'React', 'Python'],
    overview: 'A full-stack IoT solution that bridges physical factory equipment with a real-time cloud monitoring platform, enabling predictive maintenance and zero-downtime operations.',
    problem: 'The client had no visibility into machine health or energy consumption on the factory floor, leading to unexpected breakdowns and costly unplanned downtime.',
    solution: 'We deployed an MQTT-based sensor network connected to AWS IoT Core, with a React dashboard for real-time monitoring, anomaly detection, and automated alert notifications.',
    features: ['Real-Time Sensor Dashboard', 'Predictive Maintenance Alerts', 'OTA Firmware Updates', 'Energy Consumption Tracking', 'Automated Downtime Reports', 'Multi-Site Support'],
    technologies: ['Arduino', 'Raspberry Pi', 'MQTT', 'AWS IoT Core', 'Python', 'FastAPI', 'React', 'InfluxDB', 'Grafana', 'Docker'],
    results: [
      { metric: 'Unplanned Downtime', value: '-68%' },
      { metric: 'Devices Connected', value: '240+' },
      { metric: 'Energy Cost Savings', value: '₱1.2M/yr' },
      { metric: 'Alert Response Time', value: '<30 seconds' },
    ],
    testimonial: {
      quote: 'We went from zero visibility to full factory transparency overnight. PROGREX built exactly what we needed.',
      author: 'Rene Villanueva',
      role: 'Plant Manager, Villanueva Industrial',
    },
  },
  {
    id: 'brainspark-app',
    slug: 'brainspark-app',
    title: 'BrainSpark',
    systemType: 'Flashcard & Quiz Learning App',
    category: 'Mobile',
    industry: 'Education',
    shortDesc: 'Adaptive flashcard and quiz learning app that helps students master any subject using spaced-repetition, mastery tracking, and timed quiz sessions — built with Flutter and Supabase.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217678/1_nxiqfg.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773984938/10_ychopg.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217678/1_nxiqfg.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217670/2_kougck.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217671/3_rmwbm2.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217675/4_ywjq3v.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217676/5_w3cyzg.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217674/6_eldeog.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217674/7_xh4uqx.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217671/8_efs3ui.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773217678/9_obgoli.png',
    ],
    tags: ['Flutter', 'Supabase', 'Dart'],
    overview: 'BrainSpark is a mobile learning app that helps users study smarter using spaced-repetition flashcards and timed quiz sessions. Users organize cards into decks by topic, track mastery progress, and review performance analytics.',
    problem: 'Traditional study methods like re-reading notes are inefficient and hard to measure. Learners struggle to identify weak areas and end up wasting time on material they already know before exams.',
    solution: 'BrainSpark combines active recall with performance tracking. Cards are flagged by difficulty, mastery is computed from accuracy scores, and study sessions surface weak cards more frequently.',
    features: [
      'Spaced-Repetition Flashcards',
      'Timed Quiz Sessions',
      'Mastery Tracking by Deck',
      'Deck Creation and Organization',
      'Difficulty-Based Card Prioritization',
      'Daily Study Goal and Streaks',
      'Quiz Performance Analytics',
      'Offline Study with Auto Sync',
      'Cross-Device Progress Sync',
      'Smart Review Reminders',
      'Dark and Light Theme',
      'Card Search and Filter',
    ],
    technologies: ['Flutter', 'Dart', 'Supabase', 'PostgreSQL'],
    results: [
      { metric: 'Quiz Completion Rate', value: '91%' },
      { metric: 'Avg Study Sessions/Day', value: '3.4' },
      { metric: 'Mastery Improvement', value: '+67%' },
      { metric: 'User Rating', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'BrainSpark completely transformed how I study. The spaced repetition system kept me focused on what actually needed review.',
      author: 'Andrea Cruz',
      role: 'College Student, UP Diliman',
    },
  },
  {
    id: 'circlo-app',
    slug: 'circlo-app',
    title: 'Circlo',
    systemType: 'Community Social Networking App',
    category: 'Mobile',
    industry: 'Social Media',
    shortDesc: 'Community-first social app for Filipino niche groups where users join circles, share posts, and engage through focused feeds designed for meaningful interaction.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226881/2_b49kvp.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226881/1_fdhgdn.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226901/2_b49kvp.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226902/3_ybp9rl.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226910/4_ljfuis.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226890/5_galahe.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226885/6_wiavkr.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226884/7_ucq5kk.png',
    ],
    tags: ['React Native', 'TypeScript', 'Firebase', 'Firestore'],
    overview: 'Circlo is a mobile social platform where users join interest-based circles, publish media posts, and discover local communities across the Philippines.',
    problem: 'Users in Cebu, Davao, and Metro Manila wanted focused community spaces without the noise of mainstream social feeds.',
    solution: 'We built circle-based feeds, live interactions, and localized discovery to keep engagement relevant and community-centered.',
    features: [
      'Interest-Based Circle Creation',
      'Circle Join and Leave Controls',
      'Media Post Publishing',
      'Threaded Comments and Replies',
      'Reaction Counters in Real Time',
      'User Profiles with Activity History',
      'Circle Discovery by Topic',
      'Push Notifications for Mentions',
      'In-App Notification Center',
      'Follow and Follower System',
      'Dark and Light Theme',
      'Offline Feed Caching',
    ],
    technologies: ['React Native', 'TypeScript', 'Firebase', 'Firestore'],
    results: [
      { metric: 'Monthly Active Users', value: '28,000+' },
      { metric: 'Avg Session Duration', value: '14.8 min' },
      { metric: '7-Day Retention', value: '62%' },
      { metric: 'App Store Rating', value: '4.7/5' },
    ],
    testimonial: {
      quote: 'Circlo helped us build active local communities without relying on noisy mainstream platforms.',
      author: 'Mika De Leon',
      role: 'Founder, Circlo Philippines',
    },
  },
  {
    id: 'eventora-app',
    slug: 'eventora-app',
    title: 'Eventora',
    systemType: 'Event Discovery and Ticketing App',
    category: 'Mobile',
    industry: 'Events and Entertainment',
    shortDesc: 'End-to-end event app for discovery, bookings, and organizer operations, used by local organizers in Metro Manila, Clark, and Iloilo.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226894/2_ufkg2o.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226894/1_rujvuz.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226907/2_ufkg2o.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226905/3_sz1odn.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226899/4_ymmoo0.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226910/5_eub5vh.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226895/6_m7n10j.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226897/7_mr4ho0.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773226891/8_izjo3h.png',
    ],
    tags: ['Flutter', 'Dart', 'Appwrite', 'PostgreSQL'],
    overview: 'Eventora centralizes event creation, attendee management, ticket issuance, and live organizer updates in one mobile experience.',
    problem: 'Local organizers relied on spreadsheets and messaging apps, causing overbooking and poor attendee communication.',
    solution: 'We delivered mobile-first ticketing, QR validation, and live announcement tools for smooth event operations.',
    features: [
      'Event Discovery by Category',
      'Location-Based Event Search',
      'Organizer Event Creation Panel',
      'Tiered Ticket Booking Flow',
      'QR Ticket Wallet',
      'Real-Time Seat Availability',
      'Event Bookmarking',
      'Calendar Date Filtering',
      'Organizer Guest List Management',
      'QR Scan Check-In Mode',
      'Event Announcement Push Alerts',
      'Post-Event Rating Prompt',
    ],
    technologies: ['Flutter', 'Dart', 'Appwrite', 'PostgreSQL'],
    results: [
      { metric: 'Tickets Processed', value: '52,000+' },
      { metric: 'Check-In Time Reduction', value: '-71%' },
      { metric: 'No-Show Reduction', value: '-29%' },
      { metric: 'Organizer Satisfaction', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'Eventora removed the chaos from our event days and made ticket management effortless.',
      author: 'Jules Mercado',
      role: 'Operations Lead, Manila Event Guild',
    },
  },
  {
    id: 'fittrail-app',
    slug: 'fittrail-app',
    title: 'FitTrail',
    systemType: 'Workout and Fitness Tracking App',
    category: 'Mobile',
    industry: 'Health and Fitness',
    shortDesc: 'Native Android workout tracker for gym users with progression analytics, smart session logging, and offline-first performance.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982028/2_ylpfwk.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982028/1_zqaioy.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982029/2_ylpfwk.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982029/3_ofki2v.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982029/4_wmse2l.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982030/5_kgdtk6.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982030/6_nsvwab.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982029/7_s0dfd7.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982029/8_en5jwh.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982030/9_zm7nie.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982028/10_euuhjj.png',
    ],
    tags: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase'],
    overview: 'FitTrail helps users log workouts quickly, track strength progression, and stay consistent with intelligent session tools.',
    problem: 'Serious gym users needed a distraction-free app focused on logging and progress instead of social feed features.',
    solution: 'We built an offline-first Android app with structured workout logging, rest timers, and progression dashboards.',
    features: [
      'Custom Exercise Library',
      'Workout Session Builder',
      'Set, Rep, and Weight Logging',
      'In-Session Rest Timer',
      'Workout History Timeline',
      'Strength Progress Charts',
      'Body Weight Tracking',
      'Superset Grouping',
      'Previous Session Snapshot',
      'Cloud Backup and Restore',
      'Health Data Sync',
      'Offline Workout Mode',
    ],
    technologies: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase'],
    results: [
      { metric: 'Weekly Active Users', value: '11,400+' },
      { metric: 'Avg Workouts Logged/User', value: '4.1/week' },
      { metric: 'Data Loss Incidents', value: '0 reported' },
      { metric: 'Play Store Rating', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'FitTrail is exactly what lifters need: fast logging, clear progress, no unnecessary clutter.',
      author: 'Paolo Ramirez',
      role: 'Head Coach, IronLab QC',
    },
  },
  {
    id: 'habitforge-app',
    slug: 'habitforge-app',
    title: 'HabitForge',
    systemType: 'Habit Tracking and Routine App',
    category: 'Mobile',
    industry: 'Productivity',
    shortDesc: 'Habit and routine tracker built for long-term behavior change with streak analytics and smart reminder logic.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982046/2_oinafj.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982046/1_ejwxk0.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982046/2_oinafj.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982046/3_nsxkva.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982046/4_bvykmy.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982050/5_auue3o.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982050/6_lbmu5f.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982050/7_yqnqq0.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982050/8_rpjp40.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982050/9_drqdn7.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982045/10_bsu8yc.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982045/11_glra74.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982045/12_yfz7ko.png',
    ],
    tags: ['Flutter', 'Dart', 'Supabase', 'PostgreSQL'],
    overview: 'HabitForge helps users design routines, complete daily habits, and understand consistency patterns through visual analytics.',
    problem: 'Users struggled to maintain routines because most trackers offered basic checkboxes without meaningful feedback.',
    solution: 'We created a data-backed habit system with routines, streak protection, and trend visualizations to sustain momentum.',
    features: [
      'Habit Creation with Custom Frequency',
      'Routine Grouping by Time Block',
      'One-Tap Daily Check-In',
      'Current and Longest Streak Tracking',
      'Yearly Habit Heatmap View',
      'Weekly Completion Analytics',
      'Milestone Celebrations',
      'Streak Protection Alerts',
      'Per-Habit Reminder Scheduling',
      'Calendar Completion View',
      'Drag-and-Drop Habit Reordering',
      'Offline Check-In Queue',
    ],
    technologies: ['Flutter', 'Dart', 'Supabase', 'PostgreSQL'],
    results: [
      { metric: 'Avg 30-Day Retention', value: '69%' },
      { metric: 'Daily Check-Ins', value: '41,000+' },
      { metric: 'Avg Habit Completion', value: '78%' },
      { metric: 'User Rating', value: '4.7/5' },
    ],
    testimonial: {
      quote: 'HabitForge helped our users stay consistent because the progress feedback is very clear and motivating.',
      author: 'Angela Co',
      role: 'Product Owner, BetterDays PH',
    },
  },
  {
    id: 'insightly-app',
    slug: 'insightly-app',
    title: 'Insightly',
    systemType: 'Business Analytics Dashboard App',
    category: 'Mobile',
    industry: 'Business Intelligence',
    shortDesc: 'Mobile KPI dashboard that consolidates business metrics into clear, decision-ready insights for teams and executives.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982078/2_mgk4sc.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982078/1_vgzebd.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982081/2_mgk4sc.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982080/3_ph2nsf.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982079/4_eqj6hu.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982078/5_qrb87r.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982085/6_jyzfdb.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982083/7_irr2uk.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982085/8_frov6r.png',
    ],
    tags: ['Flutter', 'Dart', 'REST API', 'PostgreSQL'],
    overview: 'Insightly delivers KPI cards, trend reporting, and actionable insight summaries for fast daily business decision-making.',
    problem: 'Executives had to switch between multiple BI tools and spreadsheets to get a complete performance picture.',
    solution: 'We built one mobile analytics cockpit with goal tracking, report snapshots, and alert-style insight summaries.',
    features: [
      'KPI Dashboard Cards',
      'Weekly Revenue Trend View',
      'Monthly Comparison Reports',
      'Traffic Source Breakdown',
      'Goal Progress Tracking',
      'Status Labels by Goal',
      'Insight Feed by Priority',
      'Date Range Filtering',
      'Executive Summary Snapshots',
      'Alert Cards for Anomalies',
      'Profile and Notification Settings',
      'Cross-Platform Mobile and Desktop Build',
    ],
    technologies: ['Flutter', 'Dart', 'REST API', 'PostgreSQL'],
    results: [
      { metric: 'Decision Reporting Time', value: '-63%' },
      { metric: 'Daily Active Managers', value: '1,900+' },
      { metric: 'Goal Tracking Adoption', value: '84%' },
      { metric: 'Client Satisfaction', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'Insightly gave our leadership one trusted dashboard and eliminated manual KPI reporting.',
      author: 'Franco Velasco',
      role: 'COO, Atlas Retail Group',
    },
  },
  {
    id: 'moodleaf-app',
    slug: 'moodleaf-app',
    title: 'MoodLeaf',
    systemType: 'Mood Tracking and Journaling App',
    category: 'Mobile',
    industry: 'Mental Wellness',
    shortDesc: 'Private mood and journal app with trend detection and emotional analytics built for daily self-awareness habits.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982091/2_pwlgqu.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982091/1_oywvp7.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982089/2_pwlgqu.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982090/3_j0radc.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982088/4_cqg0hk.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982090/5_wnkezo.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982088/6_krve6o.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982089/7_uaimtf.png',
    ],
    tags: ['Flutter', 'Dart', 'Appwrite', 'PostgreSQL'],
    overview: 'MoodLeaf helps users track emotions, log private notes, and identify recurring life factors that affect well-being.',
    problem: 'Users and wellness coaches lacked structured mood history, making it difficult to detect emotional patterns over time.',
    solution: 'We delivered a secure mood journal with analytics, tag correlations, reminders, and private-by-design data handling.',
    features: [
      'Daily Mood Check-In',
      'Mood Intensity Slider',
      'Tagged Journal Entries',
      'Monthly Mood Calendar',
      'Mood History Search',
      'Streak Tracking',
      'Weekly and Monthly Trends',
      'Tag Correlation Insights',
      'Time-of-Day Mood Analysis',
      'Encrypted Journal Content',
      'Daily Reminder Notifications',
      'Anonymous Trial Mode',
    ],
    technologies: ['Flutter', 'Dart', 'Appwrite', 'PostgreSQL'],
    results: [
      { metric: 'Daily Log Consistency', value: '74%' },
      { metric: 'Weekly Active Users', value: '9,600+' },
      { metric: '30-Day Retention', value: '58%' },
      { metric: 'User Rating', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'MoodLeaf made emotional tracking practical and safe for our counseling program participants.',
      author: 'Dr. Nina Esteban',
      role: 'Clinical Psychologist, MindCare PH',
    },
  },
  {
    id: 'noteharbor-app',
    slug: 'noteharbor-app',
    title: 'NoteHarbor',
    systemType: 'Rich Note-Taking and Organization App',
    category: 'Mobile',
    industry: 'Productivity',
    shortDesc: 'Native Android notes app with rich text editing, tagging, and fast cloud sync for professionals and students.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982094/2_yjyrzz.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982094/1_xfl1tr.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982095/2_yjyrzz.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982094/3_a2s7zn.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982095/4_cklxh8.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982095/5_cchz7x.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982096/6_dlqwrq.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982096/7_n7b1yb.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982099/8_ucagtx.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982100/9_art9ug.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982094/10_zbyc70.png',
    ],
    tags: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase'],
    overview: 'NoteHarbor combines rich text writing, deep organization tools, and offline-first speed in a modern Android experience.',
    problem: 'Users needed a full-featured notes app without expensive subscription walls and slow web-based sync behavior.',
    solution: 'We built a local-first notes platform with structured tags, folders, full-text search, and reliable cloud synchronization.',
    features: [
      'Rich Text Note Editor',
      'Pinned Notes',
      'Folder and Tag Organization',
      'Archive and Trash Workflow',
      '30-Day Recovery Window',
      'Word Count and Metadata',
      'Full-Text Search',
      'Smart Sort and Filters',
      'Home Screen Shortcuts',
      'Real-Time Multi-Device Sync',
      'Offline Note Editing',
      'Theme and Preference Settings',
    ],
    technologies: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase'],
    results: [
      { metric: 'Notes Created', value: '1.3M+' },
      { metric: 'Search Response Time', value: '<120 ms' },
      { metric: 'Sync Success Rate', value: '99.6%' },
      { metric: 'Play Store Rating', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'NoteHarbor is fast, reliable, and organized exactly how power users want it.',
      author: 'Rafael Ong',
      role: 'Founder, StudyStack PH',
    },
  },
  {
    id: 'pantrypilot-app',
    slug: 'pantrypilot-app',
    title: 'PantryPilot',
    systemType: 'Pantry and Grocery Management App',
    category: 'Mobile',
    industry: 'Household and Consumer',
    shortDesc: 'Smart pantry inventory and grocery planning app that reduces household food waste with expiry and low-stock automation.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982102/2_v0ngvs.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982102/1_grde5n.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982102/2_v0ngvs.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982103/3_xznrvb.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982103/4_ltpmfn.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982107/5_fdjk2o.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982105/6_nu9jtc.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982106/7_fgkdir.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982107/8_kpcfkf.png',
    ],
    tags: ['React Native', 'TypeScript', 'Supabase', 'PostgreSQL'],
    overview: 'PantryPilot lets households track inventory, detect expiring items, and auto-generate shopping lists based on real usage.',
    problem: 'Families frequently overbought groceries and missed expiry dates due to manual, unstructured pantry tracking.',
    solution: 'We created barcode-assisted inventory, shared household lists, and automated alerts for expiry and restocking.',
    features: [
      'Pantry Inventory Dashboard',
      'Barcode Product Scanning',
      'Manual Item Entry',
      'Auto Low-Stock Detection',
      'Expiry Date Tracking',
      'Shared Household Access',
      'Smart Shopping List Builder',
      'Shopping List Check-Off Flow',
      'Household Member Roles',
      'Category and Name Filtering',
      'Offline List Caching',
      'Expiry and Restock Alerts',
    ],
    technologies: ['React Native', 'TypeScript', 'Supabase', 'PostgreSQL'],
    results: [
      { metric: 'Food Waste Reduction', value: '-38%' },
      { metric: 'Monthly Active Households', value: '7,200+' },
      { metric: 'Missed Restocks', value: '-57%' },
      { metric: 'User Rating', value: '4.7/5' },
    ],
    testimonial: {
      quote: 'PantryPilot helped our users save money every month by preventing duplicate and expired purchases.',
      author: 'Mariane Flores',
      role: 'Product Manager, HomeFlow PH',
    },
  },
  {
    id: 'pingnest-app',
    slug: 'pingnest-app',
    title: 'PingNest',
    systemType: 'Real-Time Group Messaging App',
    category: 'Mobile',
    industry: 'Communication',
    shortDesc: 'Fast chat app for Filipino teams and communities with channels, direct messages, and real-time presence tracking.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982113/2_kcz9pe.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982113/1_svycls.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982115/2_kcz9pe.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982112/3_hbej67.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982111/4_zribxj.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982112/5_mneee6.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982115/6_ednqke.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982117/7_ucdzfc.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982117/8_hiajz5.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982118/9_q5u7pm.png',
    ],
    tags: ['React Native', 'TypeScript', 'Firebase', 'Realtime Database'],
    overview: 'PingNest delivers low-latency chat, channel collaboration, and presence indicators for small teams and communities.',
    problem: 'Small organizations needed a simple chat platform that was lighter than enterprise tools but more structured than SMS groups.',
    solution: 'We launched a focused real-time messaging app with channels, DMs, reactions, and push notifications.',
    features: [
      'Group Channel Creation',
      'One-to-One Direct Messages',
      'Real-Time Message Delivery',
      'Media and File Attachments',
      'Message Reactions',
      'Read Receipt Indicators',
      'Online Presence Status',
      'Mention and Reply Support',
      'Unread Notification Badges',
      'Push Notifications',
      'Message Search and Pagination',
      'Offline Message Queue',
    ],
    technologies: ['React Native', 'TypeScript', 'Firebase', 'Realtime Database'],
    results: [
      { metric: 'Messages Sent/Month', value: '3.6M+' },
      { metric: 'Median Delivery Latency', value: '<400 ms' },
      { metric: 'Team Adoption', value: '420 groups' },
      { metric: 'User Rating', value: '4.7/5' },
    ],
    testimonial: {
      quote: 'PingNest gave our distributed teams a focused communication space without unnecessary complexity.',
      author: 'Kenneth Chua',
      role: 'Operations Director, BuildWorks PH',
    },
  },
  {
    id: 'pocketpulse-app',
    slug: 'pocketpulse-app',
    title: 'PocketPulse',
    systemType: 'Personal Finance and Budgeting App',
    category: 'Mobile',
    industry: 'Fintech',
    shortDesc: 'Native Android budgeting app that tracks spending, account balances, and monthly financial health with offline-first reliability.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982120/2_liyxyi.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982120/1_j6uts5.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982124/2_liyxyi.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982126/3_dat6ee.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982124/4_y7arc6.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982125/5_ar07ci.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982127/6_pxedhd.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982128/7_uq5myw.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982120/8_dst2lq.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982121/9_lnwpdh.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982122/10_pmcviu.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982123/11_iyem0a.png',
    ],
    tags: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase'],
    overview: 'PocketPulse helps users manage budgets, monitor spending, and understand monthly cash flow without subscription paywalls.',
    problem: 'Many Filipinos tracked budgets manually in spreadsheets, making daily money management inconvenient and inconsistent.',
    solution: 'We built a local-first finance app with budget controls, multi-account tracking, and optional secure cloud backup.',
    features: [
      'Income and Expense Logging',
      'Custom Budget Categories',
      'Monthly Budget Limits',
      'Multiple Account Tracking',
      'Net Worth Summary',
      'Transaction Search and Filters',
      'Category Spending Charts',
      'Cash Flow Trend Reports',
      'Budget Threshold Alerts',
      'Recurring Summary Notifications',
      'Optional Cloud Backup',
      'Offline Financial Tracking',
    ],
    technologies: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase'],
    results: [
      { metric: 'Monthly Transactions Logged', value: '890,000+' },
      { metric: 'Budget Overruns Reduced', value: '-33%' },
      { metric: 'Monthly Active Users', value: '24,500+' },
      { metric: 'Play Store Rating', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'PocketPulse made personal budgeting practical for users who never stuck to spreadsheet tracking.',
      author: 'Erika Mendoza',
      role: 'Head of Product, PesoWise PH',
    },
  },
  {
    id: 'savora-app',
    slug: 'savora-app',
    title: 'Savora',
    systemType: 'Recipe and Meal Planning App',
    category: 'Mobile',
    industry: 'Food and Lifestyle',
    shortDesc: 'Recipe discovery and weekly meal planner app that turns saved dishes into structured shopping-ready meal plans.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982131/2_j5wfva.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982131/1_zkhggh.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982134/2_j5wfva.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982138/3_fzkycu.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982135/4_f5csmq.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982131/5_fxzxod.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982136/6_wcjihb.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982135/7_iicflf.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982134/8_bv0gsb.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982139/9_ysoarf.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982137/10_wrwn0a.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982131/11_tqeox2.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982130/12_jh2bcm.png',
    ],
    tags: ['Flutter', 'Dart', 'Appwrite', 'PostgreSQL'],
    overview: 'Savora helps users find recipes, build weekly meal plans, and auto-generate shopping lists from planned meals.',
    problem: 'Home cooks managed recipes, meal planning, and grocery lists across separate tools, creating weekly friction.',
    solution: 'We combined discovery, planning, and shopping in one app flow tailored to everyday cooking routines.',
    features: [
      'Recipe Feed by Cuisine',
      'Advanced Recipe Search',
      'Recipe Save to Collections',
      'Weekly Meal Calendar',
      'Drag-and-Drop Meal Planning',
      'Serving Size Adjuster',
      'Auto Shopping List Generation',
      'Ingredient Quantity Merge',
      'Shopping List Category Grouping',
      'Recipe Ratings and Reviews',
      'Sunday Planning Reminder',
      'Offline Recipe Cache',
    ],
    technologies: ['Flutter', 'Dart', 'Appwrite', 'PostgreSQL'],
    results: [
      { metric: 'Weekly Meal Plans Created', value: '18,000+' },
      { metric: 'Shopping Prep Time Saved', value: '-46%' },
      { metric: 'Recipe Save Rate', value: '72%' },
      { metric: 'User Rating', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'Savora gave our users a complete meal workflow from recipe discovery to grocery checkout.',
      author: 'Chef Lianne Cruz',
      role: 'Content Director, Kusina Daily',
    },
  },
  {
    id: 'skypeek-app',
    slug: 'skypeek-app',
    title: 'SkyPeek',
    systemType: 'Weather Forecast and Alert App',
    category: 'Mobile',
    industry: 'Weather and Utilities',
    shortDesc: 'Modern weather app with hourly forecasts, radar maps, and severe weather alerts for major Philippine cities and provinces.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982141/2_pwlmyz.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982141/1_ktwyty.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982147/2_pwlmyz.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982147/3_cvdvkx.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982142/4_owtdxh.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982145/5_yy4rja.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982143/6_gxmdrd.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982144/7_jojjiq.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982148/8_wfrmfb.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982146/9_ozpzj8.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982140/10_vfrghj.png',
    ],
    tags: ['React Native', 'TypeScript', 'Expo', 'REST API'],
    overview: 'SkyPeek provides detailed weather conditions, forecast breakdowns, and proactive alerts for changing weather risks.',
    problem: 'Users needed a clear, ad-light weather app with detailed local forecasts and meaningful severe condition alerts.',
    solution: 'We built a weather app that combines polished UI, robust forecast data, and location-based alert logic.',
    features: [
      'Current Weather Conditions',
      '48-Hour Forecast Timeline',
      '7-Day Forecast Cards',
      'UV Index Risk Guidance',
      'Air Quality Monitoring',
      'Rain and Wind Indicators',
      'Saved Location Management',
      'Location Search and Geocoding',
      'Interactive Radar Map',
      'Severe Weather Alerts',
      'Temperature Unit Toggle',
      'Offline Forecast Cache',
    ],
    technologies: ['React Native', 'TypeScript', 'Expo', 'REST API'],
    results: [
      { metric: 'Daily Forecast Checks', value: '110,000+' },
      { metric: 'Alert Open Rate', value: '68%' },
      { metric: 'Saved Locations/User', value: '3.1 avg' },
      { metric: 'App Rating', value: '4.7/5' },
    ],
    testimonial: {
      quote: 'SkyPeek became our users preferred weather app because it is fast, accurate, and easy to read.',
      author: 'Harvey Tan',
      role: 'Founder, KlimaTech PH',
    },
  },
  {
    id: 'tasknest-app',
    slug: 'tasknest-app',
    title: 'TaskNest',
    systemType: 'Task and Workspace Management App',
    category: 'Mobile',
    industry: 'Productivity and Collaboration',
    shortDesc: 'Task manager combining personal planning and lightweight team workspaces with recurring schedules and reliable reminders.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982150/2_ntebxo.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982150/1_sbzss1.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982152/2_ntebxo.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982153/3_fyenk6.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982154/4_bu2p7n.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982155/5_xdc0gx.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982156/6_fsupk0.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982156/7_qsmkfk.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982157/8_wgpubd.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982158/9_gaba9z.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982150/10_jpfj2s.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982152/11_utcit3.png',
    ],
    tags: ['Kotlin', 'Jetpack Compose', 'Supabase', 'PostgreSQL'],
    overview: 'TaskNest unifies personal to-dos and shared team tasks in a mobile-first system optimized for consistency and execution.',
    problem: 'Users switched between simple to-do apps and heavy PM tools, creating fragmented workflows and missed deadlines.',
    solution: 'We designed a hybrid productivity platform with personal lists, team workspaces, and dependable reminder automation.',
    features: [
      'Task Creation with Priorities',
      'Subtask Checklists',
      'Recurring Task Rules',
      'Today and Upcoming Views',
      'Bulk Task Actions',
      'Quick Capture Inbox',
      'Workspace Board View',
      'Task Assignment by Member',
      'Task Comment Threads',
      'Invite Link Collaboration',
      'Exact Reminder Scheduling',
      'Offline Personal Task Mode',
    ],
    technologies: ['Kotlin', 'Jetpack Compose', 'Supabase', 'PostgreSQL'],
    results: [
      { metric: 'Tasks Completed/Month', value: '1.1M+' },
      { metric: 'Missed Deadlines', value: '-41%' },
      { metric: 'Active Workspaces', value: '3,800+' },
      { metric: 'User Rating', value: '4.8/5' },
    ],
    testimonial: {
      quote: 'TaskNest gave us the right balance of personal productivity and team visibility in one app.',
      author: 'Lara Dimaano',
      role: 'Operations Manager, Vertex Creatives PH',
    },
  },
  {
    id: 'tradeloop-app',
    slug: 'tradeloop-app',
    title: 'TradeLoop',
    systemType: 'Peer-to-Peer Marketplace App',
    category: 'Mobile',
    industry: 'E-Commerce Marketplace',
    shortDesc: 'Local marketplace app for buying, selling, and trading second-hand items with structured offers and in-app deal chat.',
    image: 'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982159/2_bimfaa.png',
    images: [
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982159/1_gjjqjl.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982162/2_bimfaa.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982162/3_lpixib.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982164/4_kvvqyc.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982163/5_bau44o.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982166/6_vt2dso.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982165/7_fnz9zl.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982167/8_sewqve.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982167/9_mbvgqw.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982161/10_yrmzvx.png',
      'https://res.cloudinary.com/dlu2bqrda/image/upload/v1773982160/11_qw0lro.png',
    ],
    tags: ['Flutter', 'Dart', 'Supabase', 'PostgreSQL'],
    overview: 'TradeLoop powers trusted local commerce with listing workflows, offer negotiation, and transaction reputation scoring.',
    problem: 'Existing classified apps had poor mobile UX and low trust, making local buy-and-sell transactions difficult to close.',
    solution: 'We built a marketplace centered on verified profiles, structured offer states, and real-time buyer-seller communication.',
    features: [
      'Listing Creation with Photos',
      'Cash or Trade Preference Options',
      'Category and Distance Filters',
      'Watchlist and Price Drop Alerts',
      'Structured Offer Submission',
      'Counter-Offer Workflow',
      'Real-Time Deal Chat',
      'Listing Expiry and Relist Prompts',
      'Buyer and Seller Ratings',
      'Trust Badge Indicators',
      'Listing Report and Moderation',
      'Map-Based Listing Discovery',
    ],
    technologies: ['Flutter', 'Dart', 'Supabase', 'PostgreSQL'],
    results: [
      { metric: 'Listings Published', value: '95,000+' },
      { metric: 'Deal Completion Rate', value: '64%' },
      { metric: 'Avg Time to First Offer', value: '3.2 hrs' },
      { metric: 'User Rating', value: '4.7/5' },
    ],
    testimonial: {
      quote: 'TradeLoop made local buy-and-sell safer and more structured for both new and experienced sellers.',
      author: 'Jerome Villanueva',
      role: 'Co-Founder, TradeLoop PH',
    },
  },
]




