import fs from 'node:fs/promises'
import path from 'node:path'
import { services, systems, testimonials, team, faqs, projects, blogs } from '../lib/mockData'
import { ADMIN_PERMISSION_KEYS, ADMIN_PERMISSION_LABELS } from '../lib/server/permissions'

function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return `'${String(value).replace(/'/g, "''")}'`
}

function arr(values: string[] | undefined | null): string {
  if (!values || values.length === 0) return "'{}'::text[]"
  const escaped = values.map((v) => `"${String(v).replace(/"/g, '\\"')}"`)
  return `'${`{${escaped.join(',')}}`.replace(/'/g, "''")}'::text[]`
}

function j(value: unknown): string {
  return `${q(JSON.stringify(value ?? {}))}::jsonb`
}

function normalizeCategories(category: unknown): string[] {
  if (Array.isArray(category)) return category.map(String)
  if (typeof category === 'string') return [category]
  return []
}

async function main() {
  const schemaPath = path.join(process.cwd(), 'lib', 'server', 'schema.sql')
  const schemaSql = await fs.readFile(schemaPath, 'utf8')

  const lines: string[] = []

  lines.push('-- PROGREX full Supabase setup SQL')
  lines.push('-- Generated by scripts/export-supabase-sql.ts')
  lines.push('begin;')
  lines.push('')
  lines.push(schemaSql.trim())
  lines.push('')

  lines.push('-- Permissions + owner role + admin user')
  for (const key of ADMIN_PERMISSION_KEYS) {
    lines.push(
      `insert into permissions(key, label) values (${q(key)}, ${q(ADMIN_PERMISSION_LABELS[key])}) on conflict (key) do update set label = excluded.label;`
    )
  }

  lines.push(`
insert into roles(name, description, is_system)
values ('Owner', 'Full platform control', true)
on conflict (name) do update set description = excluded.description;
`)

  lines.push(`
insert into role_permissions(role_id, permission_key, can_read, can_write, can_delete)
select r.id, p.key, true, true, true
from roles r
cross join permissions p
where r.name = 'Owner'
on conflict (role_id, permission_key)
do update set can_read = excluded.can_read, can_write = excluded.can_write, can_delete = excluded.can_delete, updated_at = now();
`)

  lines.push(`
insert into admin_users(email, full_name, password_hash, role_id, is_active)
select 'admin@progrex.cloud', 'System Admin', crypt('ChangeMe123!', gen_salt('bf', 12)), r.id, true
from roles r
where r.name = 'Owner'
on conflict (email)
do update set full_name = excluded.full_name, password_hash = excluded.password_hash, role_id = excluded.role_id, is_active = true, updated_at = now();
`)

  lines.push('-- Content seed (services, projects, team, systems, testimonials, faqs, blogs)')

  for (const [index, service] of services.entries()) {
    const details = {
      description: service.description,
      process: service.process,
      technologies: service.technologies,
      deliverables: service.deliverables,
      idealFor: service.idealFor,
      highlights: service.highlights,
      faqs: service.faqs,
    }

    lines.push(
      `insert into services(slug, title, short_desc, icon, color, details, sort_order, is_published) values (${q(service.slug)}, ${q(service.title)}, ${q(service.shortDesc)}, ${q(service.icon)}, ${q(service.color)}, ${j(details)}, ${index}, true) on conflict (slug) do update set title = excluded.title, short_desc = excluded.short_desc, icon = excluded.icon, color = excluded.color, details = excluded.details, sort_order = excluded.sort_order, is_published = excluded.is_published, updated_at = now();`
    )
  }

  for (const [index, project] of projects.entries()) {
    const details = {
      images: project.images,
      overview: project.overview,
      problem: project.problem,
      solution: project.solution,
      features: project.features,
      technologies: project.technologies,
      results: project.results,
      testimonial: project.testimonial,
    }

    lines.push(
      `insert into projects(slug, title, system_type, industry, categories, tags, image, short_desc, details, is_featured, feature_order, is_published) values (${q(project.slug)}, ${q(project.title)}, ${q(project.systemType)}, ${q(project.industry)}, ${arr(normalizeCategories(project.category))}, ${arr(project.tags)}, ${q(project.image)}, ${q(project.shortDesc)}, ${j(details)}, ${index < 13 ? 'true' : 'false'}, ${index}, true) on conflict (slug) do update set title = excluded.title, system_type = excluded.system_type, industry = excluded.industry, categories = excluded.categories, tags = excluded.tags, image = excluded.image, short_desc = excluded.short_desc, details = excluded.details, is_featured = excluded.is_featured, feature_order = excluded.feature_order, is_published = excluded.is_published, updated_at = now();`
    )
  }

  lines.push('delete from team_members;')
  for (const [index, member] of team.entries()) {
    lines.push(
      `insert into team_members(name, role, bio, avatar, linkedin, github, portfolio, sort_order, is_active) values (${q(member.name)}, ${q(member.role)}, ${q(member.bio)}, ${q(member.avatar)}, ${q(member.linkedin)}, ${q(member.github)}, ${q(member.portfolio)}, ${index}, true);`
    )
  }

  for (const [index, system] of systems.entries()) {
    const details = {
      features: system.features,
      faqs: system.faqs,
      pricing: system.pricing,
      screenshots: system.screenshots,
    }

    lines.push(
      `insert into ready_made_systems(slug, name, category, industry, tagline, short_desc, image, has_demo, details, sort_order, is_published) values (${q(system.slug)}, ${q(system.name)}, ${q(system.category)}, ${q(system.industry)}, ${q(system.tagline)}, ${q(system.shortDesc)}, ${q(system.image)}, ${system.hasDemo ? 'true' : 'false'}, ${j(details)}, ${index}, true) on conflict (slug) do update set name = excluded.name, category = excluded.category, industry = excluded.industry, tagline = excluded.tagline, short_desc = excluded.short_desc, image = excluded.image, has_demo = excluded.has_demo, details = excluded.details, sort_order = excluded.sort_order, is_published = excluded.is_published, updated_at = now();`
    )
  }

  lines.push('delete from testimonials;')
  for (const [index, item] of testimonials.entries()) {
    lines.push(
      `insert into testimonials(name, role, avatar, quote, rating, company, sort_order, is_published) values (${q(item.name)}, ${q(item.role)}, ${q(item.avatar)}, ${q(item.quote)}, ${item.rating}, ${q(item.company)}, ${index}, true);`
    )
  }

  lines.push('delete from site_faqs;')
  for (const [index, item] of faqs.entries()) {
    lines.push(
      `insert into site_faqs(question, answer, sort_order, is_published) values (${q(item.question)}, ${q(item.answer)}, ${index}, true);`
    )
  }

  for (const blog of blogs) {
    lines.push(
      `insert into blogs(slug, title, category, author_name, author_role, author_avatar, published_at, read_time, image, excerpt, tags, content, related_posts, meta_title, meta_description, keywords, is_published) values (${q(blog.slug)}, ${q(blog.title)}, ${q(blog.category)}, ${q(blog.author.name)}, ${q(blog.author.role)}, ${q(blog.author.avatar)}, ${q(blog.date)}, ${q(blog.readTime)}, ${q(blog.image)}, ${q(blog.excerpt)}, ${arr(blog.tags)}, ${q(blog.content)}, ${arr(blog.relatedPosts)}, ${q(blog.metaTitle)}, ${q(blog.metaDescription)}, ${arr(blog.keywords)}, true) on conflict (slug) do update set title = excluded.title, category = excluded.category, author_name = excluded.author_name, author_role = excluded.author_role, author_avatar = excluded.author_avatar, published_at = excluded.published_at, read_time = excluded.read_time, image = excluded.image, excerpt = excluded.excerpt, tags = excluded.tags, content = excluded.content, related_posts = excluded.related_posts, meta_title = excluded.meta_title, meta_description = excluded.meta_description, keywords = excluded.keywords, is_published = excluded.is_published, updated_at = now();`
    )
  }

  lines.push('commit;')

  const outPath = path.join(process.cwd(), 'scripts', 'supabase-full-setup.sql')
  await fs.writeFile(outPath, lines.join('\n'), 'utf8')
  console.log(`Generated ${outPath}`)
}

void main()
